### ISSUE TITLE
Website redirects to walgreens-csc.pwnhealth.org/swn-character-creator/

### ISSUE THREAD

**Issue by PatPeter** [noah-sennett/swn-character-creator#1]
Hi Noah. There seems to be something wrong with the website. When we open: https://noah-sennett.github.io/swn-character-creator/

It redirects to: https://walgreens-csc.pwnhealth.org/swn-character-creator/

**Comment by noah-sennett** [comment]
The issue was tied to my experimenting with my user github Pages. The erroneous redirecta has been eliminated; I'll look into hosting solutions independent of github in the future.

**Comment by PatPeter** [comment]
Well, I can say that GitHub is good because if you hadn't used GitHub, I never would have found out how to contact you about it being broken! :D
