### ISSUE TITLE
Did the site go down?

### ISSUE THREAD

**Issue by Hiddenisme** [noah-sennett/swn-character-creator#10]
![image](https://github.com/user-attachments/assets/bf0415a9-f72e-4b71-82ba-a5729708ad62)

Recently this is what I am getting when I try to access the site...

**Comment by noah-sennett** [comment]
There's some issue with the hosting---I'm working on it now. In the meantime, I've restored a copy of the site hosted on GitHub; you can access it here [https://noah-sennett.github.io/swn-character-creator/](https://noah-sennett.github.io/swn-character-creator/)

**Comment by noah-sennett** [comment]
Hosting issues resolved; the site should be back up. You may need to refresh your cache

**Comment by Hiddenisme** [comment]
Thank you, thank you!
