### ISSUE TITLE
Adding permalink code like pd2skills.com

### ISSUE THREAD

**Issue by PatPeter** [noah-sennett/swn-character-creator#2]
This is a fantastic character builder which is why I was concerned when I saw it go down. The only problem is my friend is the DM and needs the character sheets, but his internet is really slow and it's always a hassle to download them and upload them to him.

Would it be possible to get permalink code like http://pd2skills.com has? As in, when you're making changes to the character builder, it makes changes to the URL that can be permanently linked to other people? Would make sharing character sheets a lot easier.

**Comment by noah-sennett** [comment]
Permalinks added; use the "Share" button in the lower left to generate a customized link for your character sheet.
